DROP TABLE  IF EXISTS  MONEY_TRANSFERS;

CREATE TABLE MONEY_TRANSFERS
(
  ID NUMERIC(19) PRIMARY KEY NOT NULL,
  CREATIONDATE TIMESTAMP NOT NULL,
  REQUEST BLOB NOT NULL
);
CREATE UNIQUE INDEX MONEY_TRANSFERS_ID_uindex ON MONEY_TRANSFERS (ID);